apiVersion: v1
kind: Service
metadata:
  name: smartops-agent
  namespace: smartops-system
spec:
  type: NodePort
  selector:
    app: smartops-agent
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31200
      protocol: TCP
