apiVersion: v1
kind: Service
metadata:
  name: smartops-agent-lb
  namespace: smartops-system
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: smartops-agent
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
