'use strict';

// Seed script - populates Cosmos DB with the 20 products from the existing frontend
const mongoose = require('mongoose');

const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/ammazone-catalog';

const productData = [
  { productId:"aurora-x1-headphones", name:"Aurora X1 Spatial Headphones", category:"Audio", price:249, rating:4.8, reviewsCount:128, stock:18, featured:true, colors:["Midnight","Glacier","Coral"], shortDescription:"Adaptive noise control with cinema-grade spatial sound.", description:"Aurora X1 wraps studio-level clarity into a lightweight frame with adaptive noise control, gesture playback, and a battery tuned for long workdays or red-eye flights.", badge:"Best Seller", specs:["40-hour battery","Bluetooth 5.4","Dual-device pairing","Fast USB-C charge"], images:["/images/real/headphones-1.jpg","/images/real/headphones-2.jpg","/images/real/headphones-3.jpg"] },
  { productId:"pulse-fit-watch", name:"Pulse Fit Pro Watch", category:"Wearables", price:189, rating:4.7, reviewsCount:94, stock:24, featured:true, colors:["Slate","Ivory","Ocean"], shortDescription:"Recovery insights, AMOLED clarity, and 7-day endurance.", description:"Designed for creators and athletes alike, Pulse Fit Pro tracks recovery, focus sessions, and workouts with a bright edge-to-edge display and ultra-smooth haptics.", badge:"New", specs:["AMOLED display","Water resistant","Heart-rate & sleep tracking","Wireless charging"], images:["/images/real/watch-1.jpg","/images/real/watch-2.jpg","/images/real/watch-3.jpg"] },
  { productId:"studio-lamp-air", name:"Studio Lamp Air", category:"Home Tech", price:129, rating:4.6, reviewsCount:71, stock:12, featured:false, colors:["Cloud","Charcoal"], shortDescription:"Ambient desk lighting with wireless charging built in.", description:"Studio Lamp Air balances focused brightness with warm ambient scenes and a concealed wireless charging pad, turning any workspace into a calm production zone.", badge:"Editor Pick", specs:["Qi charging","Touch dimmer","Warm-to-cool light","Minimal aluminum frame"], images:["/images/real/lamp-1.jpg","/images/real/lamp-2.jpg","/images/real/lamp-3.jpg"] },
  { productId:"terra-commute-backpack", name:"Terra Commute Backpack", category:"Lifestyle", price:149, rating:4.5, reviewsCount:58, stock:20, featured:true, colors:["Sand","Forest","Black"], shortDescription:"Structured carry system for creators on the move.", description:"Terra Commute gives you clean access pockets, weather-ready fabric, and a padded 16-inch device sleeve without feeling bulky on trains, flights, or campus runs.", badge:"Popular", specs:["16-inch laptop sleeve","Water-resistant weave","Quick-access top pocket","Breathable straps"], images:["/images/real/backpack-1.jpg","/images/real/backpack-2.jpg","/images/real/backpack-3.jpg"] },
  { productId:"solis-mini-speaker", name:"Solis Mini Speaker", category:"Audio", price:99, rating:4.4, reviewsCount:136, stock:33, featured:false, colors:["Sky","Stone","Berry"], shortDescription:"Pocket-sized sound with all-day battery and bold tone.", description:"Small footprint, room-filling sound. Solis Mini is tuned for crisp vocals and warm bass, making it a perfect everyday speaker for desks, kitchens, and quick outings.", badge:"Value", specs:["18-hour battery","Stereo pair mode","USB-C","Splash resistant"], images:["/images/real/speaker-2.jpg","/images/real/speaker-2.jpg","/images/real/speaker-3.jpg"] },
  { productId:"nova-14-laptop", name:"Nova 14 Creator Laptop", category:"Computing", price:1399, rating:4.9, reviewsCount:46, stock:7, featured:true, colors:["Graphite","Silver"], shortDescription:"Thin performance laptop crafted for design and editing.", description:"Nova 14 pairs a vivid high-refresh display with all-day efficiency and quiet thermals, making it ideal for designers, developers, and hybrid teams working anywhere.", badge:"Flagship", specs:["14-inch 3K display","16GB unified memory","1TB SSD","AI-assisted battery modes"], images:["/images/real/laptop-1.jpg","/images/real/laptop-2.jpg","/images/real/laptop-3.jpg"] },
  { productId:"luma-phone-case", name:"Luma Magnetic Case", category:"Accessories", price:49, rating:4.3, reviewsCount:81, stock:41, featured:false, colors:["Mint","Carbon","Rose"], shortDescription:"Precision magnetic alignment with premium tactile grip.", description:"Luma Magnetic Case combines soft-touch comfort, reinforced corners, and a flush camera ring into a case that feels elevated instead of bulky.", badge:"Trending", specs:["MagSafe compatible","Drop-tested corners","Matte soft-touch finish","Raised camera lip"], images:["/images/real/case-1.jpg","/images/real/case-2.jpg","/images/real/case-3.jpg"] },
  { productId:"ember-chair", name:"Ember Ergonomic Chair", category:"Home Tech", price:329, rating:4.7, reviewsCount:62, stock:9, featured:false, colors:["Graphite","Mist"], shortDescription:"Posture-focused comfort with breathable support zones.", description:"Ember Chair supports long creative sessions with a flexible lumbar system, breathable mesh back, and sculpted seat that feels supportive instead of stiff.", badge:"Limited", specs:["4D armrests","Dynamic lumbar support","Breathable mesh","Tilt lock settings"], images:["/images/real/chair-1.jpg","/images/real/chair-2.jpg","/images/real/chair-3.jpg"] },
  { productId:"aurora-open-ear-buds", name:"Aurora Open-Ear Buds", category:"Audio", price:159, rating:4.6, reviewsCount:88, stock:27, featured:false, colors:["Pearl","Graphite","Blue Mist"], shortDescription:"Lightweight buds built for calls, commute, and all-day comfort.", description:"Aurora Open-Ear Buds keep you aware of your surroundings while delivering clear vocals, punchy mids, and low-latency device switching for daily use.", badge:"Fresh Drop", specs:["Open-ear fit","ENC microphones","28-hour case battery","Fast pairing"], images:["/images/real/headphones-2.jpg","/images/real/headphones-1.jpg","/images/real/headphones-3.jpg"] },
  { productId:"solis-room-speaker", name:"Solis Room Speaker", category:"Audio", price:219, rating:4.7, reviewsCount:112, stock:16, featured:true, colors:["Stone","Midnight"], shortDescription:"A bigger wireless speaker tuned for lounge spaces and work zones.", description:"Solis Room Speaker expands the compact Solis sound into a wider, fuller profile with richer bass, smoother voice pickup, and seamless multi-room pairing.", badge:"Featured", specs:["Multi-room audio","30W tuned drivers","Voice assistant ready","USB-C charging"], images:["/images/real/speaker-3.jpg","/images/real/speaker-2.jpg","/images/real/speaker-3.jpg"] },
  { productId:"pulse-fit-lite", name:"Pulse Fit Lite", category:"Wearables", price:129, rating:4.5, reviewsCount:73, stock:34, featured:false, colors:["Ivory","Navy","Lilac"], shortDescription:"Core health tracking with a cleaner, lighter everyday profile.", description:"Pulse Fit Lite focuses on comfort-first wear, giving you fitness tracking, sleep insights, and dependable battery life in a slimmer format.", badge:"Everyday Pick", specs:["5-day battery","Sleep tracking","Step & workout modes","Water resistant"], images:["/images/real/watch-2.jpg","/images/real/watch-1.jpg","/images/real/watch-3.jpg"] },
  { productId:"nova-air-13", name:"Nova Air 13", category:"Computing", price:1099, rating:4.8, reviewsCount:67, stock:11, featured:false, colors:["Silver","Blue Gray"], shortDescription:"Ultra-light laptop designed for fast collaboration and travel.", description:"Nova Air 13 balances portability and performance with a crisp display, silent thermals, and all-day endurance for teams that move between meetings and deep work.", badge:"Lightweight", specs:["13-inch 2.8K display","12-hour battery","512GB SSD","Fast charging"], images:["/images/real/laptop-2.jpg","/images/real/laptop-1.jpg","/images/real/laptop-3.jpg"] },
  { productId:"nova-dock-station", name:"Nova Dock Station", category:"Computing", price:179, rating:4.4, reviewsCount:54, stock:29, featured:false, colors:["Silver","Charcoal"], shortDescription:"Minimal docking hub for creators with multiple displays and drives.", description:"Nova Dock Station simplifies your desk with clean cable routing, fast external storage support, and multi-port connectivity that keeps a mobile setup feeling permanent.", badge:"Desk Essential", specs:["Dual-display support","USB-C PD","SD card slot","2.5Gb Ethernet"], images:["/images/real/laptop-3.jpg","/images/real/laptop-2.jpg","/images/real/laptop-1.jpg"] },
  { productId:"luma-slim-wallet-case", name:"Luma Slim Wallet Case", category:"Accessories", price:69, rating:4.5, reviewsCount:61, stock:37, featured:false, colors:["Carbon","Sand","Blush"], shortDescription:"Magnetic wallet-style case with a cleaner silhouette.", description:"Luma Slim Wallet Case adds card carry and drop protection without sacrificing the minimal in-hand feel that made the original Luma popular.", badge:"Upgrade", specs:["Card slot module","MagSafe ready","Drop protection","Soft-touch shell"], images:["/images/real/case-2.jpg","/images/real/case-1.jpg","/images/real/case-3.jpg"] },
  { productId:"terra-travel-sling", name:"Terra Travel Sling", category:"Lifestyle", price:89, rating:4.4, reviewsCount:44, stock:32, featured:false, colors:["Black","Stone","Forest"], shortDescription:"Compact crossbody carry for passports, cables, and daily tools.", description:"Terra Travel Sling organizes compact gear with quick-access pockets, a secure back compartment, and a form that stays sleek whether packed light or heavy.", badge:"Travel Ready", specs:["Hidden rear pocket","Weather-resistant shell","Adjustable strap","Tablet sleeve"], images:["/images/real/backpack-2.jpg","/images/real/backpack-1.jpg","/images/real/backpack-3.jpg"] },
  { productId:"ember-desk-chair-pro", name:"Ember Desk Chair Pro", category:"Home Tech", price:429, rating:4.8, reviewsCount:53, stock:8, featured:true, colors:["Graphite","Cloud"], shortDescription:"Enhanced lumbar support and refined posture tuning for long sessions.", description:"Ember Desk Chair Pro extends the Ember line with a deeper recline range, softer seat contouring, and precision support adjustments for hybrid work setups.", badge:"Pro Series", specs:["4D lumbar tuning","Headrest support","Silent casters","Premium fabric"], images:["/images/real/chair-2.jpg","/images/real/chair-1.jpg","/images/real/chair-3.jpg"] },
  { productId:"studio-lamp-mini", name:"Studio Lamp Mini", category:"Home Tech", price:89, rating:4.3, reviewsCount:49, stock:26, featured:false, colors:["White","Graphite"], shortDescription:"Compact accent lighting for smaller desks and bedside spaces.", description:"Studio Lamp Mini brings the clean visual language of the larger Air model into a tighter footprint with soft dimming and color-temperature presets.", badge:"Compact", specs:["Touch dimming","Warm/cool presets","USB-C powered","Small-footprint base"], images:["/images/real/lamp-2.jpg","/images/real/lamp-1.jpg","/images/real/lamp-3.jpg"] },
  { productId:"nova-sleeve-14", name:"Nova Sleeve 14", category:"Accessories", price:59, rating:4.6, reviewsCount:57, stock:39, featured:false, colors:["Slate","Ivory","Ocean"], shortDescription:"Padded laptop sleeve with soft-touch lining and sleek carry profile.", description:"Nova Sleeve 14 protects notebooks and tablets with dense padding, a smooth zip track, and a refined exterior that fits naturally into backpacks or totes.", badge:"Editor Pick", specs:["14-inch fit","Soft microfibre lining","Water-resistant outer","Accessory pocket"], images:["/images/real/laptop-1.jpg","/images/real/backpack-1.jpg","/images/real/laptop-2.jpg"] },
  { productId:"pulse-sport-band", name:"Pulse Sport Band", category:"Wearables", price:39, rating:4.2, reviewsCount:98, stock:56, featured:false, colors:["Blue","Graphite","Coral"], shortDescription:"Breathable replacement band built for training and warm-weather wear.", description:"Pulse Sport Band upgrades comfort with perforated, sweat-friendly material and a secure clasp that stays comfortable from workouts to commuting.", badge:"Add-On", specs:["Soft silicone","Quick release","Sweat resistant","Universal Pulse fit"], images:["/images/real/watch-3.jpg","/images/real/watch-2.jpg","/images/real/watch-1.jpg"] },
  { productId:"solis-desk-mic-speaker", name:"Solis Desk Mic Speaker", category:"Audio", price:149, rating:4.5, reviewsCount:65, stock:22, featured:false, colors:["Stone","Blue Gray"], shortDescription:"Compact conference speaker tuned for calls, content, and quick setup.", description:"Solis Desk Mic Speaker blends clean voice pickup, balanced near-field sound, and a desk-friendly profile for modern meeting rooms and home offices.", badge:"Workday Pick", specs:["360-degree mic array","USB-C + Bluetooth","Voice isolation","Portable shell"], images:["/images/real/speaker-3.jpg","/images/real/speaker-2.jpg","/images/real/headphones-1.jpg"] },
];

async function seed() {
  try {
    await mongoose.connect(MONGO_URI, { tls: true, retryWrites: false, directConnection: false });
    console.log('Connected to Cosmos DB');

    const Product = require('../models/Product');
    await Product.deleteMany({});
    await Product.insertMany(productData);
    console.log(`Seeded ${productData.length} products successfully`);
    process.exit(0);
  } catch (err) {
    console.error('Seed failed:', err.message);
    process.exit(1);
  }
}

seed();
